### ISSUE TITLE
Hamburger menu close button refinements

### ISSUE THREAD

**Issue by tomayac** [tomayac/SVGcode#44]
- It gets rendered outside of the menu on iOS.
- It should remain at a fixed position when scrolling.

**Comment by tomayac** [comment]
Hello @georapbox! Are you interested in working on this?

**Comment by georapbox** [comment]
Hi @tomayac! I'll have a look when I find some time!

**Comment by tomayac** [comment]
Absolutely no pressure, take whatever time you need, or just say "no", too.

**Comment by tomayac** [comment]
The iOS issue:

![image](https://user-images.githubusercontent.com/145676/145781273-93d81ae1-5775-4385-b1ba-4c52f75d9fc4.png)

**Comment by georapbox** [comment]
Regarding having the button in fixed position, there are might be some edge cases that the button might fall over other elements. This can happen in very small viewports in combination to other languages, eg Greek where the words are longer. The minimum I can do is to provide a background color to button so that at least it does not look bad if that happens. Would that be a viable solution? Otherwise, I guess that we would need to follow another approach, like wrapping the button in another fixed positioned element with a background color that would act as a menu header and push the menu's content a few pixels lower.

**Comment by tomayac** [comment]
I guess in the interest of screen real estate, adding a background color and making the button float on top would work best here.

**Comment by tomayac** [comment]
Fixed via #45
